# Generated by Django 4.0.4 on 2022-04-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='semester',
            new_name='category',
        ),
    ]
