# Generated by Django 4.0.4 on 2022-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_rename_semester_hotel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='score',
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
