# Generated by Django 4.0.4 on 2022-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_remove_hotel_score_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='score',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='4', max_length=1),
        ),
    ]
